import datetime

from flask.cli import AppGroup

from applications.extensions import db
from applications.models import User, Role, Dept, Power

admin_cli = AppGroup("admin")

now_time = datetime.datetime.now()
userdata = [
    User(
        id=1,
        username='admin',
        password_hash='pbkdf2:sha256:150000$raM7mDSr$58fe069c3eac01531fc8af85e6fc200655dd2588090530084d182e6ec9d52c85',
        create_at=now_time,
        enable=1,
        realname='超级管理',
        remark='要是不能把握时机，就要终身蹭蹬，一事无成！',
        avatar='/static/system/admin/images/avatar.jpg',
        dept_id=1,
    ),
    User(
        id=2,
        username='test',
        password_hash='pbkdf2:sha256:150000$cRS8bYNh$adb57e64d929863cf159f924f74d0634f1fecc46dba749f1bfaca03da6d2e3ac',
        create_at=now_time,
        enable=1,
        realname='测试',
        remark='要是不能把握时机，就要终身蹭蹬，一事无成！',
        avatar='/static/system/admin/images/avatar.jpg',
        dept_id=1,
    ),
    User(
        id='3',
        username='wind',
        password_hash='pbkdf2:sha256:150000$skME1obT$6a2c20cd29f89d7d2f21d9e373a7e3445f70ebce3ef1c3a555e42a7d17170b37',
        create_at=now_time,
        enable=1,
        realname='风',
        remark='要是不能把握时机，就要终身蹭蹬，一事无成！',
        avatar='/static/system/admin/images/avatar.jpg',
        dept_id=7,
    ),
]
roledata = [
    Role(
        id=1,
        code='admin',
        name='管理员',
        enable=1,
        details='管理员',
        sort=1,
        create_time=now_time,
        isInternal='internal',
    ),
    Role(
        id=2,
        code='common',
        name='普通用户',
        enable=1,
        details='只有查看，没有增删改权限',
        sort=2,
        create_time=now_time,
        isInternal='internal',
    ),
    Role(
        id=3,
        code='factory_director',
        name='厂长',
        enable=1,
        details='工厂的职位：厂长',
        sort=3,
        isInternal='factory',
        create_time=now_time,
    ),
    Role(
        id=4,
        code='factory_vice_plant_manager',
        name='副厂长',
        enable=1,
        details='工厂的职位：副厂长',
        sort=4,
        isInternal='factory',
        create_time=now_time,
    ),
    Role(
        id=5,
        code='factory_cutting_bed',
        name='裁床',
        enable=1,
        details='工厂职位：裁床',
        sort=5,
        isInternal='factory',
        create_time=now_time,
    ),
    Role(
        id=6,
        code='factory_parking_space',
        name='车位',
        enable=1,
        details='工厂的职位：车位',
        sort=6,
        isInternal='factory',
        create_time=now_time,
    ),
    Role(
        id=7,
        code='factory_presser',
        name='烫工',
        enable=1,
        details='工厂职位：烫工',
        sort=7,
        isInternal='factory',
        create_time=now_time,
    ),
    Role(
        id=8,
        code='factory_tail',
        name='尾部',
        enable=1,
        details='工厂职位：尾部',
        sort=8,
        isInternal='factory',
        create_time=now_time,
    ),
    Role(
        id=9,
        code='factory_quality_inspector',
        name='质检员',
        enable=1,
        details='工厂职位：质检员',
        sort=9,
        isInternal='factory',
        create_time=now_time,
    )
]
deptdata = [
    Dept(
        id=1,
        parent_id=0,
        dept_name='总公司',
        sort=1,
        leader='就眠仪式',
        phone='12312345679',
        email='123qq.com',
        status=1,
        remark='这是总公司',
        create_at=now_time
    ),
    Dept(
        id=4,
        parent_id=1,
        dept_name='济南分公司',
        sort=2,
        leader='就眠仪式',
        phone='12312345679',
        email='123qq.com',
        status=1,
        remark='这是济南',
        create_at=now_time

    ),
    Dept(
        id=5,
        parent_id=1,
        dept_name='唐山分公司',
        sort=4,
        leader='mkg',
        phone='12312345679',
        email='123qq.com',
        status=1,
        remark='这是唐山',
        create_at=now_time

    ),
    Dept(
        id=7,
        parent_id=4,
        dept_name='济南分公司开发部',
        sort=5,
        leader='就眠仪式',
        phone='12312345679',
        email='123qq.com',
        status=1,
        remark='测试',
        create_at=now_time

    ),
    Dept(
        id=8,
        parent_id=5,
        dept_name='唐山测试部',
        sort=5,
        leader='mkg',
        phone='12312345679',
        email='123qq.com',
        status=1,
        remark='测试部',
        create_at=now_time

    )
]
powerdata = [
    Power(
        id=1,
        name='系统管理',
        type='0',
        code='',
        url=None,
        open_type=None,
        parent_id='0',
        icon='layui-icon layui-icon-set-fill',
        sort=1,
        create_time=now_time,
        enable=1,

    ), Power(
        id=3,
        name='用户管理',
        type='1',
        code='system:user:main',
        url='/system/user/',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon-rate',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=4,
        name='权限管理',
        type='1',
        code='system:power:main',
        url='/system/power/',
        open_type='_iframe',
        parent_id='1',
        icon=None,
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=9,
        name='角色管理',
        type='1',
        code='system:role:main',
        url='/system/role',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-username',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=12,
        name='系统监控',
        type='1',
        code='system:monitor:main',
        url='/system/monitor',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-vercode',
        sort=5,
        create_time=now_time,
        enable=1,
    ), Power(
        id=13,
        name='日志管理',
        type='1',
        code='system:log:main',
        url='/system/log',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-read',
        sort=4,
        create_time=now_time,
        enable=1,
    ), Power(
        id=17,
        name='文件管理',
        type='0',
        code='',
        url='',
        open_type='',
        parent_id='0',
        icon='layui-icon layui-icon-camera',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=18,
        name='图片上传',
        type='1',
        code='system:file:main',
        url='/system/file',
        open_type='_iframe',
        parent_id='17',
        icon='layui-icon layui-icon-camera',
        sort=5,
        create_time=now_time,
        enable=1,
    ), Power(
        id=21,
        name='权限增加',
        type='2',
        code='system:power:add',
        url='',
        open_type='',
        parent_id='4',
        icon='layui-icon layui-icon-add-circle',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=22,
        name='用户增加',
        type='2',
        code='system:user:add',
        url='',
        open_type='',
        parent_id='3',
        icon='layui-icon layui-icon-add-circle',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=23,
        name='用户编辑',
        type='2',
        code='system:user:edit',
        url='',
        open_type='',
        parent_id='3',
        icon='layui-icon layui-icon-rate',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=24,
        name='用户删除',
        type='2',
        code='system:user:remove',
        url='',
        open_type='',
        parent_id='3',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,
    ), Power(
        id=25,
        name='权限编辑',
        type='2',
        code='system:power:edit',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=26,
        name='用户删除',
        type='2',
        code='system:power:remove',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,
    ), Power(
        id=27,
        name='用户增加',
        type='2',
        code='system:role:add',
        url='',
        open_type='',
        parent_id='9',
        icon='',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=28,
        name='角色编辑',
        type='2',
        code='system:role:edit',
        url='',
        open_type='',
        parent_id='9',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=29,
        name='角色删除',
        type='2',
        code='system:role:remove',
        url='',
        open_type='',
        parent_id='9',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,
    ), Power(
        id=30,
        name='角色授权',
        type='2',
        code='system:role:power',
        url='',
        open_type='',
        parent_id='9',
        icon='',
        sort=4,
        create_time=now_time,
        enable=1,
    ), Power(
        id=31,
        name='图片增加',
        type='2',
        code='system:file:add',
        url='',
        open_type='',
        parent_id='18',
        icon='',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=32,
        name='图片删除',
        type='2',
        code='system:file:delete',
        url='',
        open_type='',
        parent_id='18',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=44,
        name='数据字典',
        type='1',
        code='system:dict:main',
        url='/system/dict',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-console',
        sort=6,
        create_time=now_time,
        enable=1,
    ), Power(
        id=45,
        name='字典增加',
        type='2',
        code='system:dict:add',
        url='',
        open_type='',
        parent_id='44',
        icon='',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=46,
        name='字典修改',
        type='2',
        code='system:dict:edit',
        url='',
        open_type='',
        parent_id='44',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=47,
        name='字典删除',
        type='2',
        code='system:dict:remove',
        url='',
        open_type='',
        parent_id='44',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,
    ), Power(
        id=48,
        name='部门管理',
        type='1',
        code='system:dept:main',
        url='/system/dept',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-group',
        sort=3,
        create_time=now_time,
        enable=1,
    ), Power(
        id=49,
        name='部门增加',
        type='2',
        code='system:dept:add',
        url='',
        open_type='',
        parent_id='48',
        icon='',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=50,
        name='部门编辑',
        type='2',
        code='system:dept:edit',
        url='',
        open_type='',
        parent_id='48',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=51,
        name='部门删除',
        type='2',
        code='system:dept:remove',
        url='',
        open_type='',
        parent_id='48',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,
    ), Power(
        id=57,
        name='邮件管理',
        type='1',
        code='system:mail:main',
        url='/system/mail',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon ',
        sort=7,
        create_time=now_time,
        enable=1,
    ), Power(
        id=58,
        name='邮件发送',
        type='2',
        code='system:mail:add',
        url='',
        open_type='',
        parent_id='57',
        icon='layui-icon layui-icon-ok-circle',
        sort=1,
        create_time=now_time,
        enable=1,
    ), Power(
        id=59,
        name='邮件删除',
        type='2',
        code='system:mail:remove',
        url='',
        open_type='',
        parent_id='57',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,
    ), Power(
        id=60,
        name='订单管理',
        type='1',
        code='system:order:main',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon layui-icon-template-1',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=61,
        name='新增订单',
        type='2',
        code='system:order:add',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon ',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=62,
        name='修改订单-订单提交',
        type='2',
        code='system:order:edit_Submitted',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon ',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=63,
        name='修改订单-裁剪(分包/完成）',
        type='2',
        code='system:order:edit_Cutting',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon layui-icon ',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=64,
        name='修改订单-缝制生产（客户）',
        type='2',
        code='system:order:edit_Sewing_client',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon ',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=65,
        name='修改订单-缝制生产（员工）',
        type='2',
        code='system:factory_order:edit_Sewing_staff',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon ',
        sort=5,
        enable=1,
        create_time=now_time,
    ), Power(
        id=66,
        name='删除订单',
        type='2',
        code='system:order:remove',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon ',
        sort=6,
        enable=1,
        create_time=now_time,
    ), Power(
        id=67,
        name='订单详情（按钮）',
        type='2',
        code='system:order:detail',
        url='/system/factory/order_management/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon layui-icon ',
        sort=7,
        enable=1,
        create_time=now_time,
    ), Power(
        id=68,
        name='订单详情（页面）',
        type='1',
        code='system:order_detail:main',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon ',
        sort=8,
        enable=1,
        create_time=now_time,
    ), Power(
        id=69,
        name='确认订单',
        type='2',
        code='system:order:verify',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon',
        sort=9,
        enable=1,
        create_time=now_time,
    ), Power(
        id=70,
        name='自制订单',
        type='2',
        code='system:order:abstain',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon',
        sort=10,
        enable=1,
        create_time=now_time,
    ), Power(
        id=71,
        name='外发订单',
        type='2',
        code='system:order:outsource',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon',
        sort=11,
        enable=1,
        create_time=now_time,
    ), Power(
        id=72,
        name='外发收货',
        type='2',
        code='system:order:outsource_receive',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon',
        sort=12,
        enable=1,
        create_time=now_time,
    ), Power(
        id=73,
        name='出货',
        type='2',
        code='system:order:delivery',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=60,
        icon='layui-icon',
        sort=13,
        enable=1,
        create_time=now_time,
    ), Power(
        id=74,
        name='新增订单详情',
        type='2',
        code='system:order:detail:add',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=68,
        icon='layui-icon layui-icon layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=75,
        name='修改订单详情',
        type='2',
        code='system:order:detail:edit',
        url='/system/factory/order_management/detail/',
        open_type='_iframe',
        parent_id=68,
        icon='layui-icon layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=76,
        name='客户管理',
        type='1',
        code='system:client:main',
        url='/system/factory/client_management/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon layui-icon-username',
        sort=5,
        enable=1,
        create_time=now_time,
    ), Power(
        id=77,
        name='新增客户',
        type='2',
        code='system:client:add',
        url='/system/factory/client_management/',
        open_type='_iframe',
        parent_id=76,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=78,
        name='修改客户',
        type='2',
        code='system:client:edit',
        url='/system/factory/client_management/',
        open_type='_iframe',
        parent_id=76,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=79,
        name='删除客户',
        type='2',
        code='system:client:remove',
        url='/system/factory/client_management/',
        open_type='_iframe',
        parent_id=76,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=80,
        name='员工管理',
        type='1',
        code='system:staff:main',
        url='/system/factory/staff_management/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon layui-icon-user',
        sort=6,
        enable=1,
        create_time=now_time,
    ), Power(
        id=81,
        name='新增员工',
        type='2',
        code='system:staff:add',
        url='/system/factory/staff_management/',
        open_type='_iframe',
        parent_id=80,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=82,
        name='修改员工',
        type='2',
        code='system:staff:edit',
        url='/system/factory/staff_management/',
        open_type='_iframe',
        parent_id=80,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=83,
        name='删除员工',
        type='2',
        code='system:staff:remove',
        url='/system/factory/staff_management/',
        open_type='_iframe',
        parent_id=80,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=84,
        name='颜色管理',
        type='1',
        code='system:color:main',
        url='/system/factory/color_management/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon layui-icon-theme',
        sort=7,
        enable=1,
        create_time=now_time,
    ), Power(
        id=85,
        name='新增颜色',
        type='2',
        code='system:color:add',
        url='/system/factory/color_management/',
        open_type='_iframe',
        parent_id=84,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=86,
        name='修改颜色',
        type='2',
        code='system:color:edit',
        url='/system/factory/color_management/',
        open_type='_iframe',
        parent_id=84,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=87,
        name='删除颜色',
        type='2',
        code='system:color:remove',
        url='/system/factory/color_management/',
        open_type='_iframe',
        parent_id=84,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=88,
        name='尺码管理',
        type='1',
        code='system:size:main',
        url='/system/factory/size_management/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon layui-icon-star',
        sort=8,
        enable=1,
        create_time=now_time,
    ), Power(
        id=89,
        name='新增尺码',
        type='2',
        code='system:size:add',
        url='/system/factory/size_management/',
        open_type='_iframe',
        parent_id=88,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=90,
        name='修改尺码',
        type='2',
        code='system:size:edit',
        url='/system/factory/size_management/',
        open_type='_iframe',
        parent_id=88,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=91,
        name='删除尺码',
        type='2',
        code='system:size:remove',
        url='/system/factory/size_management/',
        open_type='_iframe',
        parent_id=88,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=92,
        name='裁床管理',
        type='1',
        code='system:cutting_bed:main',
        url='/system/factory/cutting_bed_management/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon layui-icon layui-icon-tabs',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=93,
        name='新增裁床单',
        type='2',
        code='system:cutting_bed:add',
        url='/system/factory/cutting_bed_management/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=94,
        name='修改裁床单',
        type='2',
        code='system:cutting_bed:edit',
        url='/system/factory/cutting_bed_management/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=95,
        name='裁床单详情（按钮）',
        type='2',
        code='system:cutting_bed:detail',
        url='/system/factory/cutting_bed_management/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=96,
        name='裁床单详情（页面）',
        type='1',
        code='system:cutting_bed:detail:main',
        url='/system/factory/cutting_bed_management/detail/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon layui-icon',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=97,
        name='新增裁床单详情',
        type='2',
        code='system:cutting_bed:detail:add',
        url='/system/factory/cutting_bed_management/detail/',
        open_type='_iframe',
        parent_id=96,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=98,
        name='修改裁床单详情',
        type='2',
        code='system:cutting_bed:detail:edit',
        url='/system/factory/cutting_bed_management/detail/',
        open_type='_iframe',
        parent_id=96,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=99,
        name='派发',
        type='2',
        code='system:cutting_bed:detail:dispatch',
        url='/system/factory/cutting_bed_management/detail/',
        open_type='_iframe',
        parent_id=96,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=100,
        name='交货',
        type='2',
        code='system:cutting_bed:detail:delivery',
        url='/system/factory/cutting_bed_management/detail/',
        open_type='_iframe',
        parent_id=96,
        icon='layui-icon',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=101,
        name='厂外协作（按钮）',
        type='2',
        code='system:cutting_bed:outsource',
        url='/system/factory/cutting_bed_management/detail/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon layui-icon',
        sort=6,
        enable=1,
        create_time=now_time,
    ), Power(
        id=102,
        name='厂外协作（页面）',
        type='1',
        code='system:outsource:main',
        url='/system/factory/cutting_bed_management/outsource/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon layui-icon layui-icon',
        sort=7,
        enable=1,
        create_time=now_time,
    ), Power(
        id=103,
        name='新增厂外协作信息',
        type='2',
        code='system:cutting_bed:outsource:add',
        url='/system/factory/cutting_bed_management/outsource/',
        open_type='_iframe',
        parent_id=102,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=104,
        name='修改厂外协作信息',
        type='2',
        code='system:cutting_bed:outsource:edit',
        url='/system/factory/cutting_bed_management/outsource/',
        open_type='_iframe',
        parent_id=102,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=105,
        name='删除厂外协作信息',
        type='2',
        code='system:cutting_bed:outsource:remove',
        url='/system/factory/cutting_bed_management/outsource/',
        open_type='_iframe',
        parent_id=102,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=106,
        name='完成裁剪',
        type='2',
        code='system:cutting_bed:complete',
        url='/system/factory/cutting_bed_management/outsource/',
        open_type='_iframe',
        parent_id=92,
        icon='layui-icon',
        sort=5,
        enable=1,
        create_time=now_time,
    ), Power(
        id=107,
        name='财务统计',
        type='0',
        code='system:cutting_bed:complete',
        url='/system/factory/cutting_bed_management/outsource/',
        open_type='_iframe',
        parent_id=0,
        icon='layui-icon layui-icon-dollar',
        sort=9,
        enable=1,
        create_time=now_time,
    ), Power(
        id=108,
        name='员工工资',
        type='1',
        code='system:finance_statistics:staff_wage:main',
        url='/system/factory/finance_statistics/staff_wage/',
        open_type='_iframe',
        parent_id=107,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=109,
        name='其它开销',
        type='1',
        code='system:finance_statistics:other_expenses:main',
        url='/system/factory/finance_statistics/other_expenses/',
        open_type='_iframe',
        parent_id=107,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=110,
        name='客户回款',
        type='1',
        code='system:finance_statistics:client_payment:main',
        url='/system/factory/finance_statistics/client_payment/',
        open_type='_iframe',
        parent_id=107,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=111,
        name='收支统计',
        type='1',
        code='system:finance_statistics:statistics:main',
        url='/system/factory/finance_statistics/statistics/',
        open_type='_iframe',
        parent_id=107,
        icon='layui-icon',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=112,
        name='生成员工工资',
        type='2',
        code='system:finance_statistics:staff_wage:add',
        url='/system/factory/finance_statistics/statistics/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=113,
        name='修改员工工资',
        type='2',
        code='system:finance_statistics:staff_wage:edit',
        url='/system/factory/finance_statistics/statistics/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=114,
        name='员工绩效',
        type='2',
        code='system:finance_statistics:staff_wage:performance',
        url='/system/factory/finance_statistics/statistics/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=115,
        name='工资详情（按钮）',
        type='2',
        code='system:finance_statistics:staff_wage:detail',
        url='/system/factory/finance_statistics/statistics/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=116,
        name='工资详情 （页面）',
        type='1',
        code='system:finance_statistics:staff_wage:detail:main',
        url='/system/factory/finance_statistics/staff_wage/detail/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=5,
        enable=1,
        create_time=now_time,
    ), Power(
        id=117,
        name='设置补助',
        type='2',
        code='system:finance_statistics:staff_wage:subsidy',
        url='/system/factory/finance_statistics/staff_wage/detail/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=6,
        enable=1,
        create_time=now_time,
    ), Power(
        id=118,
        name='设置烫工单价',
        type='2',
        code='system:finance_statistics:staff_wage:set_unit_price',
        url='/system/factory/finance_statistics/staff_wage/detail/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=7,
        enable=1,
        create_time=now_time,
    ), Power(
        id=119,
        name='新增其它开销',
        type='2',
        code='system:finance_statistics:other_expenses:add',
        url='/system/factory/finance_statistics/staff_wage/detail/',
        open_type='_iframe',
        parent_id=109,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=120,
        name='其它开销-详细（按钮）',
        type='2',
        code='system:finance_statistics:other_expenses:detail',
        url='/system/factory/finance_statistics/staff_wage/detail/',
        open_type='_iframe',
        parent_id=109,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=121,
        name='其它开销-详细（页面）',
        type='1',
        code='system:finance_statistics:other_expenses:detail:main',
        url='/system/factory/finance_statistics/other_expenses/detail/',
        open_type='_iframe',
        parent_id=109,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=122,
        name='其它开销-详细-修改',
        type='2',
        code='system:finance_statistics:other_expenses:detail:edit',
        url='/system/factory/finance_statistics/other_expenses/detail/',
        open_type='_iframe',
        parent_id=121,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=123,
        name='客户回款-新增',
        type='2',
        code='system:finance_statistics:client_payment:add',
        url='/system/factory/finance_statistics/other_expenses/detail/',
        open_type='_iframe',
        parent_id=110,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=124,
        name='客户回款-设置',
        type='2',
        code='system:finance_statistics:client_payment:edit',
        url='/system/factory/finance_statistics/other_expenses/detail/',
        open_type='_iframe',
        parent_id=110,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=125,
        name='客户回款-详情（按钮）',
        type='2',
        code='system:finance_statistics:client_payment:detail',
        url='/system/factory/finance_statistics/other_expenses/detail/',
        open_type='_iframe',
        parent_id=110,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=126,
        name='客户回款-详情（页面）',
        type='1',
        code='system:finance_statistics:client_payment:detail:main',
        url='/system/factory/finance_statistics/client_payment/detail/',
        open_type='_iframe',
        parent_id=110,
        icon='layui-icon',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=129,
        name='生成收支统计',
        type='2',
        code='system:finance_statistics:statistics:create',
        url='/system/factory/finance_statistics/client_payment/detail/',
        open_type='_iframe',
        parent_id=111,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=130,
        name='新增其它收入',
        type='2',
        code='system:finance_statistics:statistics:add',
        url='/system/factory/finance_statistics/client_payment/detail/',
        open_type='_iframe',
        parent_id=111,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=131,
        name='详情（其它收入-按钮）',
        type='2',
        code='system:finance_statistics:statistics:detail',
        url='/system/factory/finance_statistics/client_payment/detail/',
        open_type='_iframe',
        parent_id=111,
        icon='layui-icon',
        sort=3,
        enable=1,
        create_time=now_time,
    ), Power(
        id=132,
        name='详情（其它收入-页面）',
        type='1',
        code='system:finance_statistics:statistics:detail:main',
        url='/system/factory/finance_statistics/statistics/detail/',
        open_type='_iframe',
        parent_id=111,
        icon='layui-icon',
        sort=4,
        enable=1,
        create_time=now_time,
    ), Power(
        id=133,
        name='修改详情',
        type='2',
        code='system:finance_statistics:statistics:detail:edit',
        url='/system/factory/finance_statistics/statistics/detail/',
        open_type='_iframe',
        parent_id=132,
        icon='layui-icon',
        sort=1,
        enable=1,
        create_time=now_time,
    ), Power(
        id=134,
        name='删除详情',
        type='2',
        code='system:finance_statistics:statistics:detail:remove',
        url='/system/factory/finance_statistics/statistics/detail/',
        open_type='_iframe',
        parent_id=132,
        icon='layui-icon',
        sort=2,
        enable=1,
        create_time=now_time,
    ), Power(
        id=135,
        name='临时工统计（按钮）',
        type='2',
        code='system:finance_statistics:staff_wage:temp_staff_count',
        url='/system/factory/finance_statistics/staff_wage/temp_staff_count/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=8,
        enable=1,
        create_time=now_time,
    ), Power(
        id=136,
        name='临时工统计（页面）',
        type='1',
        code='system:finance_statistics:staff_wage:temp_staff_count:main',
        url='/system/factory/finance_statistics/staff_wage/temp_staff_count/',
        open_type='_iframe',
        parent_id=108,
        icon='layui-icon',
        sort=9,
        enable=1,
        create_time=now_time,
    )
]


def add_user_role():
    admin_role = Role.query.filter_by(id=1).first()
    admin_user = User.query.filter_by(id=1).first()
    admin_user.role.append(admin_role)
    test_role = Role.query.filter_by(id=2).first()
    test_user = User.query.filter_by(id=2).first()
    test_user.role.append(test_role)
    db.session.commit()


def add_role_power():
    admin_powers = Power.query.filter(Power.id.in_([1, 3, 4, 9, 12, 13, 17, 18, 44, 48])).all()
    admin_user = Role.query.filter_by(id=2).first()
    for i in admin_powers:
        admin_user.power.append(i)
    db.session.commit()


@admin_cli.command("init")
def init_db():
    db.session.add_all(userdata)
    print("加载系统必须用户数据")
    db.session.add_all(roledata)
    print("加载系统必须角色数据")
    db.session.add_all(deptdata)
    print("加载系统必须部门数据")
    db.session.add_all(powerdata)
    print("加载系统必须权限数据")
    db.session.commit()
    print("基础数据存入")
    add_user_role()
    print("用户角色数据存入")
    add_role_power()
    print("角色权限数据存入")
    print("数据初始化完成,请使用run脚本运行")
